### ISSUE TITLE
Document code in oqe.py

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#10] opened 2018-01-13 03:35 UTC
Functions (and DataSet class) in oqe.py need documentation describing args, function behavior and returned values.

**Comment by philbull** [comment] 2018-01-15 20:04
This is mostly a duplicate of issue #5.

**Comment by jsdillon** [comment] 2018-01-18 18:50
(And specifically in a Jupyter Notebook format.)

**Closed** 2018-03-07 22:56 UTC
