### ISSUE TITLE
hera_sim dependence not accounted for in setup.py

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#288] opened 2020-10-01 05:19 UTC
`testing.py` relies on `hera_sim` and it is loaded in `__init__.py` so it is effectively a dependancy but it is not listed as such in `setup.py`.

Should we add it as a dependency or should we take `testing` out of `__init__.py`?

**Comment by steven-murray** [comment] 2020-10-01 14:07
This is a duplicate of #280

**Comment by philbull** [comment] 2021-03-18 09:22
Closing as duplicate.

**Closed by philbull** 2021-03-18 09:22 UTC
