### ISSUE TITLE
Cholesky like decomp for non-positive definite

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_pspec#26] opened 2018-01-25 18:35 UTC
Occasionally in our data, or noise simulations, we can end up with non-positive definitely G matrices. I've see a cholesky-like decomp before that uses SVD and QR decomopsition to filter the non-positive eigenvalues and then uses QR to get a right upper triangular matrix as the decomposed product. 

I found it originally on this stackexchange post:https://math.stackexchange.com/questions/423138/cholesky-for-non-positive-definite-matrices

not sure if we are interested in implementing something like this in addition to cholesky for those fringe cases. The returned product (when in lower left) should converge to the cholesky L I think for a positive definite G.

**Comment by acliu** [comment] 2018-01-25 21:57
Can you point me to a few example data files where G is not positive definite? I'd like to investigate this further, because G is provably positive definite. (And more than that, actually---all elements of G should be positive or zero, which is a stronger condition). Carina showed me an example from her explorations where the matrix had some imaginary components, but they were small. I would naively have hoped for less numerical noise, and I'm curious to see how bad it is for your examples.

In the past, I've also dealt with non-positive definite Cholesky problems by implementing an LDL^t decomposition (rather than a traditional Cholesky of LL^t). But I'd rather not do this if we're able to get away with it. Essentially, I'd prefer to have safeguards in place that ensure that our matrices have all the right theoretical properties as far as possible. I'd like to treat the cause rather than the symptom. (Although in the end that may not be possible).

**Comment by philbull** [comment] 2018-04-20 21:00
Any updates on this?

**Comment by acliu** [comment] 2018-04-24 18:10
I think we should go for a "wait and see" approach to see if this is generally a problem for HERA data as well. I'm gonna close this for now, and we can reopen if it becomes an issue later.

**Closed by acliu** 2018-04-24 18:10 UTC
